### ISSUE TITLE
Support for upcoming eventstream API

### ISSUE THREAD

**Issue by hansmbakker** [michielpost/Q42.HueApi#255]
Maybe you already know about it since Q42 works/worked with Signify, but likely it is not yet wide-known: The Hue bridge API started supporting push events (not yet documented).

People at https://github.com/home-assistant-libs/aiohue included support for it - there are a lot of [relevant issues/PRs](https://github.com/home-assistant-libs/aiohue/issues?q=events) but they started in https://github.com/home-assistant-libs/aiohue/pull/48.

Is this something that could be added to the Nuget package?

**Comment by michielpost** [comment]
Yes, this library will get support for the push events.
But I am going to wait for the official documentation, so it will take me less time to implement it.

**Comment by michielpost** [comment]
I just released the first version of the new `HueApi` NuGet package: https://www.nuget.org/packages/HueApi/
This package targets the new clip v2 API and can listen to the EventStream.

See the readme for a usage example: https://github.com/michielpost/Q42.HueApi#eventstream
And check out the included sample console app: https://github.com/michielpost/Q42.HueApi/tree/master/src/HueApi.ConsoleSample
