### ISSUE TITLE
Callback or Event on Lamp Change State

### ISSUE THREAD

**Issue by carlberg74** [michielpost/Q42.HueApi#263]
Hi,

Is there no api for callback/event or similar to be notified when a lamp changes state (on=>off, off=>on etc)?

Cheers

**Comment by carlberg74** [comment]
...or is "eventstream API" that?

**Comment by michielpost** [comment]
There's currently no callback or eventsream available in the Philips Hue API.
I believe they will make an eventstream available for the V2 API. The first version of the V2 API was released just recently and not yet implemented by this library.

**Comment by michielpost** [comment]
I just released the first version of the new `HueApi` NuGet package: https://www.nuget.org/packages/HueApi/
This package targets the new clip v2 API and can listen to the EventStream.

See the readme for a usage example: https://github.com/michielpost/Q42.HueApi#eventstream
And check out the included sample console app: https://github.com/michielpost/Q42.HueApi/tree/master/src/HueApi.ConsoleSample
