### ISSUE TITLE
System.ArgumentException : Requested value 'Free' was not found

### ISSUE THREAD

**Issue by AleRoe** [michielpost/Q42.HueApi#270]
Hello!

When fetching groups using GetGroupsAsync(), I see a System.ArgumentException in Newtonsoft.Json.dll with "Requested value 'Free' was not found".
I assume this is due to a missing enum value for one of the Group properties (maybe "GroupType"?).

My code still works, but it might be worth while updating the Group-class to be in sync with the JSON response from the server.

Kind regards
Alexander

**Comment by michielpost** [comment]
Can you check the json (with a proxy tool, for exmple Fiddler) and see which property holds the value of `Free`?

I see no reference of a value Free in the documentation:
https://developers.meethue.com/develop/hue-api/groupds-api/#general-group-recourse

It might be the GroupType, but it can also be the RoomClass property.

**Comment by michielpost** [comment]
Thanks, I added it to the RoomClass enum. A new release is being pushed to NuGet.

**Comment by AleRoe** [comment]
Thanks, highly appreciated!
