### ISSUE TITLE
HueApi (Clip V2 API) project to support .NET 4.6.1

### ISSUE THREAD

**Issue by spudwebb** [michielpost/Q42.HueApi#271]
My program targets .NET 4.6.2 and I currently use the Q42.HueApi packages without problems, but I would like to try the new clip v2 API. Could we make the new HueApi projects to support multiple .NET framework versions like the Q42.HueApi?

It looks like System.Net.Http.Json needs at least .NET 4.6.1, so it should probably be the minimum version
https://www.nuget.org/packages/System.Net.Http.Json

What do you think?

**Comment by michielpost** [comment]
Clip V2 targets the latest .Net framework (net6). I like the idea of a fresh new library targetting only the latest .Net version so it's able to use all new features.
Clip V2 is still in preview, not complete so not necessary to use it.

I've tried targetting .net 4.6.1, but got a lot of compile errors. 
If you can create a PR that keeps most of the code intact and targets .Net 4.6.1, I'm open to including it.

**Comment by spudwebb** [comment]
Thanks, I will create a PR.

**Comment by michielpost** [comment]
Thanks for the PR, packages are pushed to NuGet
