### ISSUE TITLE
Problem with NuGet package HueApi 0.4.42

### ISSUE THREAD

**Issue by spudwebb** [michielpost/Q42.HueApi#274]
If I download the NuGet package: https://www.nuget.org/packages/HueApi/0.4.42, the HueApi.dll located in the lib/net461 directory seems to be a .NET 6 assembly rather than a .NET 4.6.1 assembly.

**Comment by spudwebb** [comment]
also if I compare the file sizes of the dlls between version 0.3.42 and 0.4.42,  0.4.42 are a lot smaller, so there is definitely something strange with the 0.4.42 package

**Comment by michielpost** [comment]
Thanks I'll have a look. I had to update the GitHub build and publish action because the old one wasn't working anymore. Probably something gone wrong there.

**Comment by michielpost** [comment]
I made some changes to the build, it should be fixed in version `0.5.42`. Can you try it?
The file size difference is because the DLL no longer contains embedded PDB/debug files. A proper `snupkg` file is published for debug sources.

**Comment by spudwebb** [comment]
It works now with the 0.5.42 version
Thanks for the quick fix.
