### ISSUE TITLE
404 Error in eventstream for the RemoteHueApi on Clip V2

### ISSUE THREAD

**Issue by AsbjornKrogh** [michielpost/Q42.HueApi#284]
When I run the HueApi.ConsoleSample for the Eventstream localy it works completly fine. 

But when I change the LocaleHueAPI to a RemoteHueAPI I will get a "404 not found" error in the httpclient. 
I have checked my appKey and Token for the RemoteHueAPI, by succesfully turning on my light. 

Any suggestions on how to solve my problem?

**Comment by AsbjornKrogh** [comment]
FYI: Philips Hue has informed us that the remote Hue API will have the event stream

Quete "Event stream is currently not yet released on the remote API." 
 - Last line on page: https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/

**Comment by michielpost** [comment]
Cool thanks, good to know!
I'll close this issue now. When the API is added to the remote API, I will add it to the library.

**Comment by AsbjornKrogh** [comment]
Perfect - Thanks! 

And thanks for an amazing SDK!
