### ISSUE TITLE
Authenticate in API V2

### ISSUE THREAD

**Issue by gkapellmann** [michielpost/Q42.HueApi#285]
Hey, great package! 

This is more a question than an issue I guess: Is there a roadmap or an estimate of when will the Authentication might arrive for the API v2?

I know that atm we can do it with the original:
> Registration of your App and retreiving a key can be done using the original Q42.HueApi. There's no support yet in the new Clip V2 API.

Just wondering to orginize myself, maybe even try to implement it.

**Comment by michielpost** [comment]
I included a LocalHueApi.RegisterAsync static method in version 0.9.1 (now on NuGet). Let me know if this works for you.

**Comment by gkapellmann** [comment]
Ah ok! Thank you for your answer.

Yes, that will help, I will test in the next few days and let you know how it went.

Thanks!

**Comment by gkapellmann** [comment]
Yeap, works like a charm now.

One question, what is the "regResult.StreamingClientKey"? 

And a request, could "await LocalHueApi.RegisterAsync" implement a cancellation event? 
I am thinking for a timeout in case the button doesnt get pressed, to be able to catch the timeout, for example:

`using (var cancellationTokenSource = new CancellationTokenSource(5000)) {
     var regResult = await LocalHueApi.RegisterAsync(ipAddress, newUser, ID, cancellationTokenSource.Token);
 }`

**Comment by michielpost** [comment]
The `StreamingClientKey` will be filled with the streaming / entertainment key when you send `generateClientKey = true` with the RegisterAsync request. It's only needed when you want to use the streaming API.

I also added the cancellationToken. But the user should first press the button, and then do a RegisterAsync request.
If the button is not pressed, it will immediately return with a `LinkButtonNotPressedException`

**Comment by gkapellmann** [comment]
OK, thank you!

I'll test and let you know how it goes.

**Comment by gkapellmann** [comment]
Ok, this works like a charm,
Thanks!
