### ISSUE TITLE
Trying to send group commands in quick succession 

### ISSUE THREAD

**Issue by joao7yt** [michielpost/Q42.HueApi#287]
I'm trying to replicate the CS:GO C4 blinking time with Philips HUE. The blinking gets quicker progressively.

I managed to get a good result limiting the command to a single bulb, but if I select more bulbs than that, commands start to get clogged up and the bulbs struggle to even do anything. Even creating a group and using SendGroupCommandAsync to send them at once instead of looping through the selected lights.

Is there a way of sending a command to multiple lights at once as it was one (in terms of responsibiness) or is it a limitation?

Thanks!

**Comment by michielpost** [comment]
For cool light effects where you need to quickly update the state of the lights, it's best to use the Hue Entertainment API.
Here is some documentation and this repo also contains a sample app:
https://github.com/michielpost/Q42.HueApi/blob/master/EntertainmentApi.md

**Comment by joao7yt** [comment]
thank you. didn't know about that.
