### ISSUE TITLE
Activating scene in Clip V2 API

### ISSUE THREAD

**Issue by JOHNEPPILLAR** [michielpost/Q42.HueApi#290]
Question:

How do you activate a scene using the Clip v2 API?

In the v1 API, I know you can activate a scene by using:

var command = new SceneCommand {Scene = "xxxxxxxx"}
await _client.SendGroupCommandAsync(command, groupId)

**Comment by michielpost** [comment]
You can do this:
```cs
UpdateScene req = new UpdateScene()
{
  Recall = new Recall() {  Action = "active"}
};
var result = await localHueClient.UpdateSceneAsync(id, req);
```
In the next update this will be made more typesafe:
```cs
Recall = new Recall() {  Action =  SceneRecallAction.active }
```

You can use the Hue Migration Guide to see how things work with the V2 API: https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/#Scenes
