### ISSUE TITLE
Light id is fix after it connected  to the hue ? can i set it ?

### ISSUE THREAD

**Issue by qiuqingpo** [michielpost/Q42.HueApi#304]
anyone  who knows? thank you!

**Comment by michielpost** [comment]
The bridge determines the light id, you can't change it.

**Comment by qiuqingpo** [comment]
> The bridge determines the light id, you can't change it.

when I search for new lights again or turn off the light, can  the light id change  automatic？

**Comment by qiuqingpo** [comment]
> The light id does not change.

ok, thank you!
