### ISSUE TITLE
Relative rotary response only contains last event, no id etc.

### ISSUE THREAD

**Issue by wouterdevinck** [michielpost/Q42.HueApi#306]
I am guessing this should `Task<HueResponse<RelativeRotaryResource>>` rather than `Task<HueResponse<RelativeRotary>>`:

https://github.com/michielpost/Q42.HueApi/blob/9ad76ed95dc1e4d5507a5befad80ae12c5cd8c50/src/HueApi/BaseHueApi.cs#L161-L162

**Comment by michielpost** [comment]
Thanks for the bug report. It's fixed in version 1.0.1, now on NuGet.

**Comment by wouterdevinck** [comment]
Awesome, thanks!
