### ISSUE TITLE
Recall cannot be combined with "speed"

### ISSUE THREAD

**Issue by gkapellmann** [michielpost/Q42.HueApi#310]
Hi

I recently started getting this error message, I basicaly do this:

`UpdateScene req = new UpdateScene() {
    Recall = new Recall() { Action = SceneRecallAction.active },
    Speed = speed
};
var result = await localHueClient.UpdateSceneAsync(id, req);`

It was working before, but I guess something changed in a recent update? I just spottet this now.

**Comment by michielpost** [comment]
Yes I get the same error when I try to use them both at the same time:
`Recall cannot be combined with modifying 'speed'"}]}` 

So it's something that has changed on the bridge.
