### ISSUE TITLE
Temperature property has wrong JSON property name

### ISSUE THREAD

**Issue by RicoSuter** [michielpost/Q42.HueApi#312]
The serialization for temperature is broken: 

https://github.com/michielpost/Q42.HueApi/blob/310a8ba773eaf18c38a69d1fc00332b71b38b776/src/HueApi/Models/Sensors/TemperatureResource.cs#L15

should be "temperature" and not "motion".

Also the temperature value should be a double and not an int: 

![image](https://github.com/michielpost/Q42.HueApi/assets/2603405/4f4c99e0-bd05-48da-a4bd-8c49b1af25b4)

**Comment by michielpost** [comment]
Thanks for letting me know. It's fixed.
The documentation on the Hue site indicates the `temperature.temperature` property is deprecated. So I removed it completely.
The temperature value can be found in `Temperature.TemperatureReport.Temperature`. 

This change is in version 1.5.2 which is being published to NuGet right now.

**Comment by RicoSuter** [comment]
With the update I'm no longer able to access the temperature at all: 

![image](https://github.com/michielpost/Q42.HueApi/assets/2603405/72308b09-dd39-4d77-9a51-1e09609076ea)

How is the report supposed to be used? Is temperature only available via push data now?

**Comment by michielpost** [comment]
The temperature value can be found in Temperature.TemperatureReport.Temperature.

**Comment by RicoSuter** [comment]
Yes, but how do I get the TemperatureReport from a TemperatureResource?

**Comment by RicoSuter** [comment]
So the Temperature class should have a "TemperatureReport" property: 

![image](https://github.com/michielpost/Q42.HueApi/assets/2603405/d0f9c13d-c5d1-4c86-80e2-bd91fe361759)

```
public class Temperature 
{
    [JsonPropertyName("temperature_report")]
    public bool TemperatureReport { get; set; }
}
```

**Comment by michielpost** [comment]
Yes, looks like the TemperatureReport was not added with the last update. I fixed it and it's being pushed to NuGet right now.

**Comment by RicoSuter** [comment]
Btw, would also be nice if the ButtonResource would have the report property: 

![image](https://github.com/michielpost/Q42.HueApi/assets/2603405/97086074-ed9d-421f-819c-7132f66971a6)

![image](https://github.com/michielpost/Q42.HueApi/assets/2603405/af0ad9b6-be95-4464-aaab-3bcf113d1df4)

**Comment by michielpost** [comment]
Just did another update with support for the new Button properties, also added support for CameraMotion, TamperSensor and ContactSensor 👍
