### ISSUE TITLE
It it mandatory to use Hub with this?

### ISSUE THREAD

**Issue by rawatsaurabh** [michielpost/Q42.HueApi#315]
Can we directly control the Philips Hue Bulb  without the need of HuB?
[This bulb](https://www.amazon.in/Philips-Connected-Dimmable-Compatible-Assistant/dp/B07XD8G2HR/ref=sr_1_7?adgrpid=63018008590&dib=eyJ2IjoiMSJ9.Ti8XHq9d4cUW-sbJ23j0C7ynHMU3X2UbGE8-IBvChTIHaoLK5eKN88475AhAxAFsRhbU9Z9m_WCw16Qm1jeY2xZCnHpfOcWB0eokIYZZosVDw8qkQP9kVkamch6aQHpHjiP1Lao4QFyJXNc6oOqojR10IIqqJbbqY-pBWSt_Oe7K0zXkTiuAzpT5CqYjsxgcB-OKwJ5xevZ3ygZPSCoC--5_4YVnT_71PYba8x2kFn-ua1e5IsEuXlqUOD96qbbb7pQNQUN22peK2zO0rj7QeSzjIhlTcbdHlyMzsWZVFWY.tFVgMpqHyhAiJAWlla5DHFvcHQVx7o_sEZNRRg1Ggds&dib_tag=se&ext_vrnc=hi&gclid=Cj0KCQjw2uiwBhCXARIsACMvIU0pVc1f1uNRC70GWYR2ODUgANuGOKRDGaW2tOIU_B31VuI9em4-7uIaAntVEALw_wcB&hvadid=590857588785&hvdev=c&hvlocphy=9061695&hvnetw=g&hvqmt=e&hvrand=891807249350665168&hvtargid=kwd-299517165990&hydadcr=6722_2247834&keywords=philips%2Bhue%2Bbulb&qid=1713076452&sr=8-7&th=1);

**Comment by michielpost** [comment]
This library does not work with Wiz bulbs. It's only for Hue lights and communication goes through the Hue bridge.
