### ISSUE TITLE
Michiel, you're a genius

### ISSUE THREAD

**Issue by fmzwy** [michielpost/Q42.HueApi#316]
Michiel, you're a genius
I was wondering if you could write a code in C# that combines sound and light synchronization. Below is an example to help you understand what I mean:

Can you write a set of code in C# that synchronizes sound and light, combining the two in a cohesive way?

**Comment by michielpost** [comment]
This library has a lot of options to do fast interaction with lights using the Entertainment API.
When this is combined with a sound processing library, you could create something like you are suggesting, sound and light synchronization.

Steps here would be something like this:
- Find a sound processing library that outputs events (like beat events, current bpm?)
- Create light effects based on these events
- Send them to your Hue bridge using the Entertainment API.

I don't see an example attatched to your message.
