### ISSUE TITLE
group metadata is null

### ISSUE THREAD

**Issue by ahihi** [michielpost/Q42.HueApi#318]
hi,

i am using HueApi 1.4.0, as it is the last version with .NET Framework 4.6.1 support.

when i retrieve information about groups like this:

```csharp
var hue = new LocalHueApi(address, key);
var groupsResponse = await hue.GetGroupsAsync();
```

i expect to find the group names in the metadata for each group. but i am only getting a null `Metadata` field for each group. is there something else i need to do to populate this field?

**Comment by michielpost** [comment]
That is not how the new Hue API works unfortunately. Each group has an owner, this is a resource id.
You can get the name of the owner, most of the time this is a room. But for group 0 it is the bridge.
