### ISSUE TITLE
No Conversion from Color to RGBColor?

### ISSUE THREAD

**Issue by Christanoid** [michielpost/Q42.HueApi#320]
Hello,
I am currently trying to change my small project from Polling the bridge to using the EventStream.
I want to listen to changes in color and apply those to my internal dataModel. For that I need the color as an RGB or HSV value, I cannot work with the XY coordinate. From what I'm seeing the EventStream only provides a json object which can be parsed to a HueApi.Models.Color. I know that there is a color converter in this library, however it appears to only be able to convert the colors from a Light class, not directly a Color object. Did I oversee something or is this conversion missing?

Regards,
Chris

**Comment by michielpost** [comment]
Yes, you're right. This was not possible.
I've just pushed an update to NuGet, HueApi.ColorConverters version 1.7.1 now includes the option to do so:

```cs
using HueApi.ColorConverters.Original.Extensions;

var position = new XyPosition { X = 1, Y = 1 };
var hex = position.ToHex();
var rgb = position.ToRGBColor();
```

Sample test:
https://github.com/michielpost/Q42.HueApi/blob/master/src/HueApi.ColorConverters.Tests/XyPositionExtensionsTests.cs#L14-L16

If you have a HueApi.Models.Color object you can do:
`colorObj.Xy.ToHex();`

Hope this helps!

**Comment by Christanoid** [comment]
Thank you very much!
